---
title: "Exercise set 1"
author: "Claudi Lleyda Moltó"
date: "NIU: 1462908"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  chunk_output_type: console
---
```{r}
# Claudi Lleyda Moltó
# NIU: 1462908

#setwd("~/UAB/MSE/DataVisualitzation/Exercises/intro-to-R/ex1/")
#ls()
```

Exercise 1
==========

(a) Enter the data into R, as two vectors

```{r}
year <- 2012:2021
snow.cover <- c(47.5, 49.2, 46.0, 47.3, 48.8, 49.2, 46.9, 47.2, 46.4, 46.8)
```

(b) Take the logarithm of `snow.cover` and call it `log.snow.cover`

```{r}
log.snow.cover <- log(snow.cover)
```

(c) Plot `snow.cover` versus `year`

```{r}
plot(year, snow.cover, "l")
```

(d) Create a summary of the snow cover data

```{r}
summary(snow.cover)
```

Exercise 2
==========

```{r}
set.seed(1462908)

x <- sample(1:6, 100, replace=TRUE)

sum(x == 3)
x[55]
x[seq(11,19,2)]
x[x == 3] <- 1
y <- x[x > 2]
mean(sqrt(x))
z <- c(x, y)
rm(z)
```

Exercise 3
==========

```{r}
subletters <- letters[1:5]
subnums <- 1:3

paste(rep(subletters, each = 3), subnums, sep = "")
paste(subletters, rep(subnums, each = 5), sep = "")
```

Exercise 4
==========

```{r}
rincome <- scan("data/rincome.txt", character(), sep="\n", skipNul = T)

toNA = c("Don't know", "No answer", "Not applicable", "Refused")
rincome[rincome %in% toNA] <- NA

rincome.f <- factor(rincome, ordered = FALSE)
levels(rincome.f)

rincome.lv <- levels(rincome.f)
rincome.lv <- levels(relevel(factor(rincome.lv), "Lt $1000"))
rincome.lv
rincome.o <- ordered(factor(rincome, levels = rincome.lv))
summary(rincome.o)

class(rincome)
class(rincome.f)
class(rincome.lv)
class(rincome.o)
```
